#ifdef __KERNEL__
#include <linux/module.h>
#include <linux/ioctl.h>
#else
#include <stdio.h>
#include <stddef.h>
#include <sys/ioctl.h>
#endif

#include "cmd_handler.h"
#include "cp15.h"
#include "vfpu.h"
#include "psr.h"
#include "aarch64.h"

const func_table_entry func_table[] =
{
    { MS_SYSREG_MIDR, (void *)do_MIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CTR, (void *)do_CTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_TCMTR, (void *)do_TCMTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_TLBTR, (void *)do_TLBTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MPIDR, (void *)do_MPIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_REVIDR, (void *)do_REVIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_AFR0, (void *)do_AFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MMFR0, (void *)do_MMFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MMFR1, (void *)do_MMFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MMFR2, (void *)do_MMFR2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MMFR3, (void *)do_MMFR3_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PFR0, (void *)do_PFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PFR1, (void *)do_PFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ISAR0, (void *)do_ISAR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ISAR1, (void *)do_ISAR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ISAR2, (void *)do_ISAR2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ISAR3, (void *)do_ISAR3_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ISAR4, (void *)do_ISAR4_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ISAR5, (void *)do_ISAR5_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CLIDR, (void *)do_CLIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_AIDR, (void *)do_AIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CSSELR, (void *)do_CSSELR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DFR0, (void *)do_DFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CCSIDR, (void *)do_CCSIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_SCTLR, (void *)do_SCTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PRRR, (void *)do_PRRR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MAIR, (void *)do_MAIR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_MAIR0, (void *)do_MAIR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MAIR1, (void *)do_MAIR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_NMRR, (void *)do_NMRR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_TTBCR, (void *)do_TTBCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_TTBR0, (void *)do_TTBR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_TTBR0LPAE, (void *)do_TTBR0LPAE_read, FUNCTYPE_OUT_2, FUNCTYPE_BITS_32 },
    { MS_SYSREG_TTBR1, (void *)do_TTBR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_TTBR1LPAE, (void *)do_TTBR1LPAE_read, FUNCTYPE_OUT_2, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CONTEXTIDR, (void *)do_CONTEXTIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_AMAIR0, (void *)do_AMAIR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_AMAIR1, (void *)do_AMAIR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_AMAIR, (void *)do_AMAIR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_DACR, (void *)do_DACR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DCZID, (void *)do_DCZID_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_IFAR, (void *)do_IFAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_IFSR, (void *)do_IFSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ADFSR, (void *)do_ADFSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_AIFSR, (void *)do_AIFSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DFAR, (void *)do_DFAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DFSR, (void *)do_DFSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_FAR, (void *)do_FAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },

    { MS_SYSREG_PMCCFILTR, (void *)do_PMCCFILTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMCR, (void *)do_PMCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMCCNTR, (void *)do_PMCCNTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_PMCEID0, (void *)do_PMCEID0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMCEID1, (void *)do_PMCEID1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMCNTENCLR, (void *)do_PMCNTENCLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMCNTENSET, (void *)do_PMCNTENSET_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMINTENCLR, (void *)do_PMINTENCLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMINTENSET, (void *)do_PMINTENSET_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMOVSR, (void *)do_PMOVSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMOVSCLR, (void *)do_PMOVSCLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMOVSSET, (void *)do_PMOVSSET_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMSELR, (void *)do_PMSELR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMSWINC, (void *)do_PMSWINC_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMUSERENR, (void *)do_PMUSERENR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMXEVCNTR, (void *)do_PMXEVCNTR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_PMXEVTYPER, (void *)do_PMXEVTYPER_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_VBAR, (void *)do_VBAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_ISR, (void *)do_ISR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MVBAR, (void *)do_MVBAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_NSACR, (void *)do_NSACR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_SCR, (void *)do_SCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_SDER, (void *)do_SDER_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_CPACR, (void *)do_CPACR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_FCSEIDR, (void *)do_FCSEIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_RMR, (void *)do_RMR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_RVBAR, (void *)do_RVBAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_PAR, (void *)do_PAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },

    { MS_SYSREG_FPEXC, (void *)do_FPEXC_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_FPSCR, (void *)do_FPSCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_FPSID, (void *)do_FPSID_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MVFR0, (void *)do_MVFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MVFR1, (void *)do_MVFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_MVFR2, (void *)do_MVFR2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_DBGDIDR, (void *)do_DBGDIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DBGAUTHSTATUS, (void *)do_DBGAUTHSTATUS_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DBGDRAR, (void *)do_DBGDRAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_DBGDSCR, (void *)do_DBGDSCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_TPIDRPRW, (void *)do_TPIDRPRW_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_TPIDRURO, (void *)do_TPIDRURO_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_TPIDRURW, (void *)do_TPIDRURW_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },

    { MS_SYSREG_JIDR, (void *)do_JIDR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_JMCR, (void *)do_JMCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_JOSCR, (void *)do_JOSCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_TEECR, (void *)do_TEECR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_TEEHBR, (void *)do_TEEHBR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_CPUMERRSR, (void *)do_CPUMERRSR_read, FUNCTYPE_OUT_2, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_L2MERRSR, (void *)do_L2MERRSR_read, FUNCTYPE_OUT_2, FUNCTYPE_BITS_ARCH },
    { MS_SYSREG_L2ACTLR, (void *)do_L2ACTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ACTLR, (void *)do_ACTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_ACTLR2, (void *)do_ACTLR2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CPUACTLR, (void *)do_CPUACTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_L2PFR, (void *)do_L2PFR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_L2CTLR, (void *)do_L2CTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_L2ECTLR, (void *)do_L2ECTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CPUECTLR, (void *)do_CPUECTLR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_IL1DATA0, (void *)do_IL1DATA0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_IL1DATA1, (void *)do_IL1DATA1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_IL1DATA2, (void *)do_IL1DATA2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_IL1DATA3, (void *)do_IL1DATA3_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DL1DATA0, (void *)do_DL1DATA0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DL1DATA1, (void *)do_DL1DATA1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DL1DATA2, (void *)do_DL1DATA2_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DL1DATA3, (void *)do_DL1DATA3_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CBAR, (void *)do_CBAR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_ARCH },

    { MS_SYSREG_AA64AFR0, (void *)do_AA64AFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64AFR1, (void *)do_AA64AFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64DFR0, (void *)do_AA64DFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64DFR1, (void *)do_AA64DFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64ISAR0, (void *)do_AA64ISAR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64ISAR1, (void *)do_AA64ISAR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64MMFR0, (void *)do_AA64MMFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64MMFR1, (void *)do_AA64MMFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64PFR0, (void *)do_AA64PFR0_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },
    { MS_SYSREG_AA64PFR1, (void *)do_AA64PFR1_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_64 },

    { MS_SYSREG_CURRENTEL, (void *)do_CURRENTEL_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_DAIF, (void *)do_DAIF_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_FPCR, (void *)do_FPCR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_FPSR, (void *)do_FPSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_NZCV, (void *)do_NZCV_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_SPSEL, (void *)do_SPSEL_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { MS_SYSREG_APSR, (void *)do_APSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_CPSR, (void *)do_CPSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },
    { MS_SYSREG_SPSR, (void *)do_SPSR_read, FUNCTYPE_OUT_1, FUNCTYPE_BITS_32 },

    { 0, NULL, 0, 0 },
};

int
return_table_size(void)
{
    return (int)((sizeof(func_table) / sizeof(func_table_entry)) - 1);
}
